### ISSUE TITLE
Periods aren't correctly detected in Arabic. 

### ISSUE THREAD

**Issue by terw-dan** [Yoast/YoastSEO.js#1034]
This issue was reported here: https://github.com/Yoast/wordpress-seo/issues/6451
But this is something that isn't WordPress specific.

I am working on an Arabic website.
When I read your tips about how to make the post readability score good, You say to make a paragraph clear and contain less than 150 words (in 7 to 8 sentences) to make it light green.
When I do so and write two sentences in one paragraph, it tell me that the sentence is more than the amount of 100% and the light become red.
The image shows that I wrote only two sentences, which contain only 19 words in two sentences (the first is 6 words and the second is 13 words only)!!

Can you provide a link to a page which shows this issue?
http://i.imgur.com/HqQIf3Y.png
![hqqif3y](https://cloud.githubusercontent.com/assets/13615909/21958139/0f9007c8-daaf-11e6-90ad-281c0f5fd7a4.png)

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 4.0.2

The sample text used is `
هذه فقرة مكونة من جملتين فقط. الجملة الأولى مكونة من 6 كلمات فقط، بينما الجملة الثانية مكونة من 15 كلمة فقط.`

It seems the periods aren't detected properly in Arabic. 
There are a couple of different full stops depending on the language: 
http://www.fileformat.info/info/unicode/char/search.htm?q=.&preview=entity

**Comment by terw-dan** [comment]
@IreneStr could you check if all these full stops should be implemented?

**Comment by 77Math** [comment]
I have this issue also, the readability reports: 33% of the sentences contain more than 20 words, which is more than the recommended maximum of 25%. Try to shorten the sentences.

while i have many many commas and I don't know how to solve it. The blog post in Arabic also.

**Comment by ShahriarKh** [comment]
I have this issue for Persian Language

**Comment by mndhamod** [comment]
It seems like this hasn't been fixed yet. Any work arounds?

**Comment by BehroozJanfada** [comment]
Thanks Jeroen for refrencing this issue again. looking forward for the fix. @jeroenrotty

**Comment by BehroozJanfada** [comment]
any updates on this issue?

**Comment by armin-git** [comment]
I have the same issue in Persian language and Yoast incorrectly detects the number of the word in sentences and then the result will be incorrect.
it's always said 
100% of the sentences contain more than 20 words, which is more than the recommended maximum of 25%.
while I wrote two-sentence whit 20 words. Yoast makes all of the sentences and words, highlights.
![1](https://user-images.githubusercontent.com/8854504/84710624-d5238580-af79-11ea-8af1-d1e31ed8bbf8.jpg)
I guess it cannot detect dot or space in a sentence.

**Comment by armin-git** [comment]
Is there any progress? Can we use this feature in future versions? this thread is opened in 2017 until now!!

**Comment by BehroozJanfada** [comment]
I Also am waiting to see this bug fixed. It's more than 3 years now. :)

**Comment by omarreiss** [comment]
Should be fixed now.

**Comment by armin-git** [comment]
This is working properly now, but separators such as question marks, exclamation marks, or commas are still not recognized in Persian and Arabic. Do we need to open another topic for this purpose? Sorry to open this topic again.

**Comment by BehroozJanfada** [comment]
In addition to @armin-git comment, parentheses still are not recognized correctly.

**Comment by omarreiss** [comment]
@armin-git @BehroozJanfada thanks for your input! Reopening and letting our linguists know.

**Comment by manuelaugustin** [comment]
@armin-git @BehroozJanfada Good catch! Indeed these issues remained in the first version of our RTL script support. In the meantime, we've caught on to that. The problem with brackets is addressed in 14.9, and the fix for Arabic question marks and commas is scheduled for 15.0. So please let us know if you still notice any issues after Yoast SEO 15.0 has been released.

See these PRs for more detailed information:
https://github.com/Yoast/javascript/pull/815 (brackets)
https://github.com/Yoast/javascript/pull/841 (punctuation marks)

**Comment by armin-git** [comment]
@manuelaugustin Thank you very much for your attention. The cases that were announced are very effective, especially in Persian.
We are still looking forward to the release of version 15.
Please consider all symbols such as question marks, parentheses, periods, commas, and semicolons, and let us know which symbols are effective.
Other expressions such as word roots, synonyms and antonyms do not exist in the Persian version of the plugin, I wish they could be loaded and used in an XML file in the plugin.

**Comment by akoSalman** [comment]
Still the same issue and not fixed with Persian language yet.
Hoping for new update and fix.
