### ISSUE TITLE
A keyword density and counting is not accurate for subsequent focus keywords

### ISSUE THREAD

**Issue by suascat** [Yoast/YoastSEO.js#1333]
### Please give us a description of what happened.

A subsequent keyword such as **releases** does not show accurate keyword density. As **releases** shows up 3 times in the document and shows a keyword density of 1.9%.

![density](https://user-images.githubusercontent.com/9716719/33928013-66ad9efe-e00c-11e7-8d15-b11f6d651de6.png)

### Please describe what you expected to happen and why.

Subsequent keywords density and count should be accurate. Apparently, these values seem true for primary focus keyword only. 

### How can we reproduce this behavior?
1. Add content to the default WordPress editor
2. Create multiple focus keywords from Yoast SEO Metabox that exist within content
3. Save post
4. Switch between keywords tabs and observe the keyword density for each word.

### Technical info
* WordPress version: 4.9.1
* Yoast SEO Premium version: 5.9.3

**Comment by suascat** [comment]
Please inform the customer of conversation # 274590 when this conversation has been closed.

**Comment by monbauza** [comment]
It seems that the analysis for additional/subsequent focus keywords are just a copy of the results for the first keyword. This affects not only the keyword density but all checks (i.e. keyword in title and meta description, etc.)

![image](https://user-images.githubusercontent.com/9658774/33932168-868215ee-dff2-11e7-8417-ad7d6c2a39e2.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 273421 when this conversation has been closed.

**Comment by atimmer** [comment]
This has been fixed with the release of Yoast SEO Premium 5.9.4.

**Comment by rmarcano** [comment]
@atimmer It seems this issue is back? 
The secondary Focus Keywords will briefly display the correct keyword density and then goes back to show the primary keyword density percentage. See video [here](https://www.useloom.com/share/72233bf20f2c477396f1426cc5d09856). 

Note that the word "second" is not present in the content at all.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 384674 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 382879 when this conversation has been closed.
